services:
  app:
    build: .
    volumes:
      - ./application:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    env_file:
      - ./.env

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgresql-test:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql

volumes:
  postgres_data:
  postgres_data_test:
